"""enhance resume metadata

Revision ID: 0aa967fb4c35
Revises: 8aff97108fa3
Create Date: 2026-08-27 00:18:54.686108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa967fb4c35'
down_revision: Union[str, Sequence[str], None] = '8aff97108fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('primary_role', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('experience_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'experience_years')
    op.drop_column('resumes', 'primary_role')
    op.drop_column('resumes', 'summary')
    op.drop_column('resumes', 'resume_text')
    # ### end Alembic commands ###
