"""update application tracking

Revision ID: 98caabfa12cd
Revises: 0aa967fb4c35
Create Date: 2026-08-27 01:20:32.548570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98caabfa12cd'
down_revision: Union[str, Sequence[str], None] = '0aa967fb4c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.drop_constraint(op.f('applications_resume_id_fkey'), 'applications', type_='foreignkey')
    op.drop_column('applications', 'cover_message')
    op.drop_column('applications', 'match_score')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('cover_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('applications_resume_id_fkey'), 'applications', 'resumes', ['resume_id'], ['id'])
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    # ### end Alembic commands ###
